# Generated by Django 5.2.6 on 2025-10-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algorithm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('algorithm_name', models.CharField(max_length=100, verbose_name='アルゴリズム名')),
                ('algorithm_description', models.TextField(blank=True, null=True, verbose_name='アルゴリズム概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'アルゴリズム',
                'verbose_name_plural': 'アルゴリズム',
                'db_table': 'algorithm',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checklist_name', models.CharField(max_length=100, verbose_name='チェックリスト名')),
                ('checklist_description', models.TextField(blank=True, null=True, verbose_name='チェックリスト概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'チェックリスト',
                'verbose_name_plural': 'チェックリスト',
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('checklist_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_text', models.TextField(verbose_name='項目テキスト')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='codemon.checklist', verbose_name='チェックリストID')),
            ],
            options={
                'verbose_name': 'チェックリスト項目',
                'verbose_name_plural': 'チェックリスト項目',
                'db_table': 'checklist_item',
                'ordering': ['sort_order', 'checklist_item_id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=100, verbose_name='システム名')),
                ('system_description', models.TextField(blank=True, null=True, verbose_name='システム種類')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'システム',
                'verbose_name_plural': 'システム',
                'db_table': 'system',
            },
        ),
    ]
