# Generated by Django 5.2.6 on 2025-11-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_merge_0002_account_avatar_0003_add_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "algorithm_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "algorithm_name",
                    models.CharField(max_length=100, verbose_name="アルゴリズム名"),
                ),
                (
                    "algorithm_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="アルゴリズム概要"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "アルゴリズム",
                "verbose_name_plural": "アルゴリズム",
                "db_table": "algorithm",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("message_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="メッセージ本文"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="送信者",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "attachment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="chat_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="codemon.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャット添付",
                "verbose_name_plural": "チャット添付",
                "db_table": "chat_attachment",
            },
        ),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("thread_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="スレッド名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブフラグ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットスレッド",
                "verbose_name_plural": "チャットスレッド",
                "db_table": "chat_thread",
            },
        ),
        migrations.CreateModel(
            name="ChatScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="codemon.chatmessage",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="採点者",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="codemon.chatthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットスコア",
                "verbose_name_plural": "チャットスコア",
                "db_table": "chat_score",
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="codemon.chatthread",
            ),
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "checklist_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "checklist_name",
                    models.CharField(max_length=100, verbose_name="チェックリスト名"),
                ),
                (
                    "checklist_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="チェックリスト概要"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="選択フラグ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "チェックリスト",
                "verbose_name_plural": "チェックリスト",
                "db_table": "checklist",
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "checklist_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("item_text", models.TextField(verbose_name="項目テキスト")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="完了フラグ"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="codemon.checklist",
                        verbose_name="チェックリストID",
                    ),
                ),
            ],
            options={
                "verbose_name": "チェックリスト項目",
                "verbose_name_plural": "チェックリスト項目",
                "db_table": "checklist_item",
                "ordering": ["sort_order", "checklist_item_id"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="グループ名"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="グループ説明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブフラグ"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "グループ",
                "verbose_name_plural": "グループ",
                "db_table": "group",
            },
        ),
        migrations.AddField(
            model_name="chatthread",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="codemon.group",
                verbose_name="グループ",
            ),
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "オーナー"),
                            ("teacher", "教師"),
                            ("student", "学生"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="codemon.group",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "グループメンバー",
                "verbose_name_plural": "グループメンバー",
                "db_table": "group_member",
                "unique_together": {("group", "member")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_groups",
                through="codemon.GroupMember",
                to="accounts.account",
            ),
        ),
        migrations.CreateModel(
            name="ReadReceipt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="codemon.chatmessage",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "既読レシート",
                "verbose_name_plural": "既読レシート",
                "db_table": "chat_read_receipt",
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("system_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "system_name",
                    models.CharField(max_length=100, verbose_name="システム名"),
                ),
                (
                    "system_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="システム種類"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "システム",
                "verbose_name_plural": "システム",
                "db_table": "system",
            },
        ),
    ]
