# Generated by Django 5.2.6 on 2025-11-11 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="readreceipt",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chatscore",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chatscore",
            name="scorer",
        ),
        migrations.RemoveField(
            model_name="chatscore",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="chatthread",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="chatthread",
            name="group",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="group",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="group",
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="member",
        ),
        migrations.RemoveField(
            model_name="readreceipt",
            name="reader",
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="チャット名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="codemon.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="codemon.message",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ChatAttachment",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatScore",
        ),
        migrations.DeleteModel(
            name="ChatThread",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.DeleteModel(
            name="ReadReceipt",
        ),
    ]
