# Generated by Django 5.2.6 on 2026-02-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="グループパスワード"
            ),
        ),
    ]
