# Generated by Django 5.2.6 on 2026-01-26 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('codemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='実績名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('reward_coins', models.IntegerField(default=0, verbose_name='報酬コイン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績',
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coin_balance', serialize=False, to='accounts.account')),
                ('balance', models.IntegerField(default=0, verbose_name='コイン残高')),
                ('total_earned', models.IntegerField(default=0, verbose_name='累計獲得コイン')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザーコイン',
                'verbose_name_plural': 'ユーザーコイン',
                'db_table': 'user_coin',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='アクセサリー名')),
                ('category', models.CharField(choices=[('flower', '花'), ('glasses', '眼鏡'), ('hat', '帽子'), ('other', 'その他')], max_length=50, verbose_name='カテゴリ')),
                ('css_class', models.CharField(help_text='例: flower red', max_length=100, verbose_name='CSSクラス名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('unlock_coins', models.IntegerField(default=0, verbose_name='必要コイン数')),
                ('simple_style', models.JSONField(blank=True, help_text='小アイコン用のCSS設定（JSON形式）', null=True, verbose_name='簡略表示スタイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('unlock_achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codemon.achievement', verbose_name='必要実績')),
            ],
            options={
                'verbose_name': 'アクセサリー',
                'verbose_name_plural': 'アクセサリー',
                'db_table': 'accessory',
            },
        ),
        migrations.CreateModel(
            name='UserAccessory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_equipped', models.BooleanField(default=False, verbose_name='装備中')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codemon.accessory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_accessories', to='accounts.account')),
            ],
            options={
                'verbose_name': 'ユーザーアクセサリー',
                'verbose_name_plural': 'ユーザーアクセサリー',
                'db_table': 'user_accessory',
                'unique_together': {('user', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('achieved_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codemon.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.account')),
            ],
            options={
                'verbose_name': 'ユーザー実績',
                'verbose_name_plural': 'ユーザー実績',
                'db_table': 'user_achievement',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
