# Generated by Django 5.2.7 on 2025-10-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0002_checklist_is_selected'),
    ]

    operations = [
    ]
