# Generated by Django 5.2.6 on 2025-11-11 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_avatar_remove_account_type'),
        ('codemon', '0002_aiconversation_aimessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.account'),
        ),
    ]
