# Generated by Django 5.2.6 on 2026-02-02 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_group_delete_groupmember_group_groupmember_and_more"),
        ("codemon", "0002_group_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="group",
            name="owner",
        ),
        migrations.CreateModel(
            name="MessegeGroup",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="グループ名"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="グループ説明"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="グループパスワード",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="アクティブフラグ"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "メッセージグループ",
                "verbose_name_plural": "メッセージグループ",
                "db_table": "messege_group",
            },
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="codemon.messegegroup",
                verbose_name="メッセージグループ",
            ),
        ),
        migrations.CreateModel(
            name="MessegeMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "オーナー"),
                            ("teacher", "教師"),
                            ("student", "学生"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="codemon.messegegroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messege_memberships",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "メッセージグループメンバー",
                "verbose_name_plural": "メッセージグループメンバー",
                "db_table": "messege_group_member",
                "unique_together": {("group", "member")},
            },
        ),
        migrations.AddField(
            model_name="messegegroup",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_messege_groups",
                through="codemon.MessegeMember",
                to="accounts.account",
            ),
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
