# Generated by Django 5.2.6 on 2025-10-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0002_set_initial_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='選択フラグ'),
        ),
    ]
