# Generated by Django 5.2.6 on 2026-02-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_group_delete_groupmember_group_groupmember_and_more"),
        (
            "codemon",
            "0003_remove_group_members_remove_group_owner_messegegroup_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageThread",
            fields=[
                ("thread_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("participant_email", models.EmailField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_threads_owned",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別チャットスレッド",
                "verbose_name_plural": "個別チャットスレッド",
                "db_table": "direct_message_thread",
                "unique_together": {("owner", "participant_email")},
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                ("message_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sender_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.account",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="codemon.directmessagethread",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別チャットメッセージ",
                "verbose_name_plural": "個別チャットメッセージ",
                "db_table": "direct_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessegeGroupInvite",
            fields=[
                ("invite_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invited_email", models.EmailField(max_length=255)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="codemon.messegegroup",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messege_invites_sent",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "メッセージグループ招待",
                "verbose_name_plural": "メッセージグループ招待",
                "db_table": "messege_group_invite",
            },
        ),
    ]
