# Generated by Django 5.2.7 on 2025-10-30 01:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0003_auto_20251024_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('checklist_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_text', models.TextField(verbose_name='項目テキスト')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('checklist', models.ForeignKey(
                    on_delete=models.CASCADE,
                    related_name='items',
                    to='codemon.checklist',
                    verbose_name='チェックリストID'
                )),
            ],
            options={
                'db_table': 'checklist_item',
                'verbose_name': 'チェックリスト項目',
                'verbose_name_plural': 'チェックリスト項目',
                'ordering': ['sort_order', 'checklist_item_id'],
            },
        ),
    ]
