# Generated by Django 5.2.7 on 2025-11-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('codemon', '0004_create_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True, verbose_name='メッセージ本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='送信者')),
            ],
            options={
                'verbose_name': 'チャットメッセージ',
                'verbose_name_plural': 'チャットメッセージ',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='codemon.chatmessage')),
            ],
            options={
                'verbose_name': 'チャット添付',
                'verbose_name_plural': 'チャット添付',
                'db_table': 'chat_attachment',
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('thread_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='スレッド名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'チャットスレッド',
                'verbose_name_plural': 'チャットスレッド',
                'db_table': 'chat_thread',
            },
        ),
        migrations.CreateModel(
            name='ChatScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='codemon.chatmessage')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='採点者')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='codemon.chatthread')),
            ],
            options={
                'verbose_name': 'チャットスコア',
                'verbose_name_plural': 'チャットスコア',
                'db_table': 'chat_score',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='codemon.chatthread'),
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='codemon.chatmessage')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': '既読レシート',
                'verbose_name_plural': '既読レシート',
                'db_table': 'chat_read_receipt',
            },
        ),
    ]
