# Generated by Django 5.2.7 on 2025-11-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0002_aiconversation_aimessage'),
        ('codemon', '0004_merge_0002_add_group_description_0003_alter_aiconversation_user'),
    ]

    operations = [
    ]