# Generated by Django 5.2.6 on 2025-11-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0004_merge_0002_add_group_description_0003_alter_aiconversation_user'),
    ]

    operations = [
    ]
