# Generated by Django 5.2.6 on 2026-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0004_directmessagethread_directmessage_messegegroupinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatscore",
            name="advice",
            field=models.TextField(
                blank=True, null=True, verbose_name="まとめ・アドバイス"
            ),
        ),
        migrations.AddField(
            model_name="chatscore",
            name="good_points",
            field=models.TextField(blank=True, null=True, verbose_name="良かったこと"),
        ),
        migrations.AddField(
            model_name="chatscore",
            name="improvement_points",
            field=models.TextField(
                blank=True, null=True, verbose_name="惜しかったこと"
            ),
        ),
        migrations.AddField(
            model_name="chatscore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
