# Generated by Django 5.2.6 on 2026-01-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('codemon', '0004_achievement_trophy_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='reward_coins',
            field=models.IntegerField(verbose_name='報酬コイン'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achieved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='達成日時'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='accounts.account'),
        ),
    ]
