# Generated by Django 5.2.6 on 2026-02-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0005_chatscore_advice_chatscore_good_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatscore",
            name="is_checked",
            field=models.BooleanField(default=False, verbose_name="採点済みチェック"),
        ),
    ]
