# Generated by Django 5.2.7 on 2025-11-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_type'),
        ('codemon', '0005_merge_20251112_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_description',
            field=models.TextField(blank=True, null=True, verbose_name='システム詳細'),
        ),
            # ChatAttachment の CreateModel 操作を削除（既存テーブル重複エラー回避）
        # ChatThread の CreateModel 操作を削除（既存テーブル重複エラー回避）
        # ChatScore の CreateModel 操作を削除（既存テーブル重複エラー回避）
        # chatmessage モデルへの thread フィールド追加操作を削除（既存列重複エラー回避）
        # Group の CreateModel 操作を削除（既存テーブル重複エラー回避）
        # chatthread モデルへの group フィールド追加操作を削除（既存列重複エラー回避）
        # GroupMember の CreateModel 操作を削除（既存テーブル重複エラー回避）
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', through='codemon.GroupMember', to='accounts.account'),
        ),
        # ReadReceipt の CreateModel 操作を削除（既存テーブル重複エラー回避）
        migrations.CreateModel(
            name='SystemElement',
            fields=[
                ('element_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=50, verbose_name='要素タイプ')),
                ('element_label', models.CharField(blank=True, max_length=200, null=True, verbose_name='要素ラベル')),
                ('element_value', models.TextField(blank=True, null=True, verbose_name='要素値')),
                ('position_x', models.IntegerField(default=0, verbose_name='X座標')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y座標')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='幅')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高さ')),
                ('style_data', models.JSONField(blank=True, null=True, verbose_name='スタイルデータ')),
                ('element_config', models.JSONField(blank=True, null=True, verbose_name='要素設定')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='codemon.system', verbose_name='システムID')),
            ],
            options={
                'verbose_name': 'システム要素',
                'verbose_name_plural': 'システム要素',
                'db_table': 'system_element',
                'ordering': ['sort_order', 'element_id'],
            },
        ),
        # Attachment の DeleteModel 操作を削除（KeyError回避）
        # Chat の DeleteModel 操作を削除（KeyError回避）
        # Message の DeleteModel 操作を削除（KeyError回避）
    ]
