# Generated by Django 5.2.6 on 2026-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0005_alter_achievement_reward_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='consecutive_ai_chat_days',
            field=models.IntegerField(default=0, verbose_name='連続AI会話日数'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_ai_chat_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終AI会話日'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_accessories_purchased',
            field=models.IntegerField(default=0, verbose_name='購入アクセサリー数'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_checklist_items_completed',
            field=models.IntegerField(default=0, verbose_name='完了チェック項目数'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_checklists_created',
            field=models.IntegerField(default=0, verbose_name='作成チェックリスト数'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('system', 'システム作成'), ('algorithm', 'アルゴリズム作成'), ('login', 'ログイン'), ('consecutive_login', '連続ログイン'), ('ai_chat', 'AI会話'), ('ai_chat_consecutive', 'AI連続会話'), ('checklist_create', 'チェックリスト作成'), ('checklist_complete', 'チェックリスト完了'), ('accessory', 'アクセサリー')], default='system', max_length=20, verbose_name='カテゴリー'),
        ),
    ]
