# Generated by Django 5.2.7 on 2025-11-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_type'),
        ('codemon', '0005_merge_20251112_1108'),
    ]

    operations = [
        # このマイグレーションは既に0001_initialで作成されたモデルと重複するため、
        # システム説明フィールドの変更のみを保持
        migrations.AlterField(
            model_name='system',
            name='system_description',
            field=models.TextField(blank=True, null=True, verbose_name='システム詳細'),
        ),
    ]
