# Generated by Django 5.2.6 on 2026-02-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0006_userstats_consecutive_ai_chat_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
