# Generated by Django 5.2.7 on 2025-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0006_remove_chat_created_by_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='blockly_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Blockly XML'),
        ),
    ]
