# Generated by Django 5.2.6 on 2026-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0006_chatscore_is_checked"),
        ("codemon", "0007_checklist_due_date"),
    ]

    operations = []
