# Generated by Django 5.2.7 on 2025-11-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0005_merge_20251112_1216'),
        ('codemon', '0005_merge_20251113_0945'),
        ('codemon', '0007_algorithm_blockly_xml'),
    ]

    operations = [
    ]
