# Generated by Django 5.2.6 on 2026-02-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('codemon', '0007_checklist_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_logged_in', models.BooleanField(default=False, verbose_name='初回ログイン済み')),
                ('step1_completed', models.BooleanField(default=False, verbose_name='STEP1完了（メイン→システム）')),
                ('step2_completed', models.BooleanField(default=False, verbose_name='STEP2完了（システム→アルゴリズム）')),
                ('step3_completed', models.BooleanField(default=False, verbose_name='STEP3完了（チェックリスト→トロフィー→ショップ）')),
                ('all_tutorials_completed', models.BooleanField(default=False, verbose_name='全チュートリアル完了')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to='accounts.account', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チュートリアル進行状況',
                'verbose_name_plural': 'チュートリアル進行状況',
                'db_table': 'tutorial_progress',
            },
        ),
    ]
