# Generated by Django 5.2.6 on 2026-02-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0008_merge_20260205_1425"),
        ("codemon", "0008_tutorialprogress"),
    ]

    operations = []
