# Generated by Django 5.2.6 on 2025-11-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0006_add_blockly_xml'),
        ('codemon', '0008_merge_20251121_1233'),
    ]

    operations = [
    ]