# Generated by Django 5.2.6 on 2025-11-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0005_merge_20251112_1216'),
        ('codemon', '0009_merge_0006_add_blockly_xml_0008_merge_20251121_1233'),
    ]

    operations = [
    ]
