# Generated by Django 5.2.6 on 2026-02-06 11:56

from django.db import migrations


def create_achievements(apps, schema_editor):
    """実績データを自動作成（既存データがある場合はスキップ）"""
    Achievement = apps.get_model('codemon', 'Achievement')
    
    # 既に実績データが存在する場合はスキップ
    if Achievement.objects.exists():
        print("✅ 実績データは既に存在します。スキップします。")
        return
    
    print("🚀 実績データを自動作成します...")
    
    achievements_data = [
        # ===== ログイン実績（累計） =====
        {'category': 'login', 'tier': 'bronze', 'name': '初ログイン', 'description': '初回ログイン', 'target_count': 1, 'reward_coins': 100, 'icon': '👋', 'display_order': 10},
        {'category': 'login', 'tier': 'silver', 'name': '3日の友', 'description': '累計3日ログイン', 'target_count': 3, 'reward_coins': 200, 'icon': '📅', 'display_order': 11},
        {'category': 'login', 'tier': 'gold', 'name': '10日の友', 'description': '累計10日ログイン', 'target_count': 10, 'reward_coins': 300, 'icon': '📅', 'display_order': 12},
        {'category': 'login', 'tier': 'platinum', 'name': '1ヶ月の友', 'description': '累計30日ログイン', 'target_count': 30, 'reward_coins': 500, 'icon': '📅', 'display_order': 13},
        {'category': 'login', 'tier': 'diamond', 'name': '2ヶ月の友', 'description': '累計60日ログイン', 'target_count': 60, 'reward_coins': 1000, 'icon': '📅', 'display_order': 14},
        
        # ===== 連続ログイン実績 =====
        {'category': 'consecutive_login', 'tier': 'bronze', 'name': '2日連続', 'description': '2日連続ログイン', 'target_count': 2, 'reward_coins': 100, 'icon': '🔥', 'display_order': 20},
        {'category': 'consecutive_login', 'tier': 'silver', 'name': '5日連続', 'description': '5日連続ログイン', 'target_count': 5, 'reward_coins': 200, 'icon': '🔥', 'display_order': 21},
        {'category': 'consecutive_login', 'tier': 'gold', 'name': '1週間連続', 'description': '7日連続ログイン', 'target_count': 7, 'reward_coins': 300, 'icon': '🔥', 'display_order': 22},
        {'category': 'consecutive_login', 'tier': 'platinum', 'name': '2週間連続', 'description': '14日連続ログイン', 'target_count': 14, 'reward_coins': 500, 'icon': '🔥', 'display_order': 23},
        {'category': 'consecutive_login', 'tier': 'diamond', 'name': '1ヶ月連続', 'description': '30日連続ログイン', 'target_count': 30, 'reward_coins': 1000, 'icon': '🔥', 'display_order': 24},
        
        # ===== システム作成実績 =====
        {'category': 'system', 'tier': 'bronze', 'name': 'システムビギナー', 'description': '1システム作成', 'target_count': 1, 'reward_coins': 100, 'icon': '⚙️', 'display_order': 30},
        {'category': 'system', 'tier': 'silver', 'name': 'システム職人', 'description': '5システム作成', 'target_count': 5, 'reward_coins': 200, 'icon': '⚙️', 'display_order': 31},
        {'category': 'system', 'tier': 'gold', 'name': 'システムマスター', 'description': '20システム作成', 'target_count': 20, 'reward_coins': 300, 'icon': '⚙️', 'display_order': 32},
        {'category': 'system', 'tier': 'platinum', 'name': 'システムエキスパート', 'description': '50システム作成', 'target_count': 50, 'reward_coins': 500, 'icon': '⚙️', 'display_order': 33},
        {'category': 'system', 'tier': 'diamond', 'name': 'システムレジェンド', 'description': '100システム作成', 'target_count': 100, 'reward_coins': 1000, 'icon': '⚙️', 'display_order': 34},
        
        # ===== アルゴリズム作成実績 =====
        {'category': 'algorithm', 'tier': 'bronze', 'name': 'アルゴリズムビギナー', 'description': '1件作成', 'target_count': 1, 'reward_coins': 100, 'icon': '🧩', 'display_order': 40},
        {'category': 'algorithm', 'tier': 'silver', 'name': 'アルゴリズム職人', 'description': '5件作成', 'target_count': 5, 'reward_coins': 200, 'icon': '🧩', 'display_order': 41},
        {'category': 'algorithm', 'tier': 'gold', 'name': 'アルゴリズムマスター', 'description': '10件作成', 'target_count': 10, 'reward_coins': 300, 'icon': '🧩', 'display_order': 42},
        {'category': 'algorithm', 'tier': 'platinum', 'name': 'アルゴリズムエキスパート', 'description': '20件作成', 'target_count': 20, 'reward_coins': 500, 'icon': '🧩', 'display_order': 43},
        {'category': 'algorithm', 'tier': 'diamond', 'name': 'アルゴリズムレジェンド', 'description': '50件作成', 'target_count': 50, 'reward_coins': 1000, 'icon': '🧩', 'display_order': 44},
        
        # ===== AI会話実績 =====
        {'category': 'ai_chat', 'tier': 'bronze', 'name': 'AI会話デビュー', 'description': '10回会話', 'target_count': 10, 'reward_coins': 100, 'icon': '💬', 'display_order': 50},
        {'category': 'ai_chat', 'tier': 'silver', 'name': 'AIフレンド', 'description': '50回会話', 'target_count': 50, 'reward_coins': 200, 'icon': '💬', 'display_order': 51},
        {'category': 'ai_chat', 'tier': 'gold', 'name': 'AI会話マスター', 'description': '100回会話', 'target_count': 100, 'reward_coins': 300, 'icon': '💬', 'display_order': 52},
        {'category': 'ai_chat', 'tier': 'platinum', 'name': 'AI会話エキスパート', 'description': '300回会話', 'target_count': 300, 'reward_coins': 500, 'icon': '💬', 'display_order': 53},
        {'category': 'ai_chat', 'tier': 'diamond', 'name': 'AI会話ベストフレンド', 'description': '1000回会話', 'target_count': 1000, 'reward_coins': 1000, 'icon': '💬', 'display_order': 54},
        
        # ===== AI連続会話実績 =====
        {'category': 'ai_chat_consecutive', 'tier': 'bronze', 'name': 'AI会話ビギナー', 'description': '2日連続会話', 'target_count': 2, 'reward_coins': 100, 'icon': '💭', 'display_order': 60},
        {'category': 'ai_chat_consecutive', 'tier': 'silver', 'name': 'AI会話パートナー', 'description': '5日連続会話', 'target_count': 5, 'reward_coins': 200, 'icon': '💭', 'display_order': 61},
        {'category': 'ai_chat_consecutive', 'tier': 'gold', 'name': 'AI会話エンスージアスト', 'description': '7日連続会話', 'target_count': 7, 'reward_coins': 300, 'icon': '💭', 'display_order': 62},
        {'category': 'ai_chat_consecutive', 'tier': 'platinum', 'name': 'AI会話マニア', 'description': '14日連続会話', 'target_count': 14, 'reward_coins': 500, 'icon': '💭', 'display_order': 63},
        {'category': 'ai_chat_consecutive', 'tier': 'diamond', 'name': 'AI会話レジェンド', 'description': '30日連続会話', 'target_count': 30, 'reward_coins': 1000, 'icon': '💭', 'display_order': 64},
        
        # ===== チェックリスト作成実績 =====
        {'category': 'checklist_create', 'tier': 'bronze', 'name': 'チェックリスト入門', 'description': '1件作成', 'target_count': 1, 'reward_coins': 100, 'icon': '📝', 'display_order': 70},
        {'category': 'checklist_create', 'tier': 'silver', 'name': 'チェックリスト職人', 'description': '5件作成', 'target_count': 5, 'reward_coins': 200, 'icon': '📝', 'display_order': 71},
        {'category': 'checklist_create', 'tier': 'gold', 'name': 'チェックリストマスター', 'description': '10件作成', 'target_count': 10, 'reward_coins': 300, 'icon': '📝', 'display_order': 72},
        {'category': 'checklist_create', 'tier': 'platinum', 'name': 'チェックリストエキスパート', 'description': '20件作成', 'target_count': 20, 'reward_coins': 500, 'icon': '📝', 'display_order': 73},
        {'category': 'checklist_create', 'tier': 'diamond', 'name': 'チェックリストレジェンド', 'description': '50件作成', 'target_count': 50, 'reward_coins': 1000, 'icon': '📝', 'display_order': 74},
        
        # ===== チェックリスト完了実績 =====
        {'category': 'checklist_complete', 'tier': 'bronze', 'name': 'タスクハンター', 'description': '10項目完了', 'target_count': 10, 'reward_coins': 100, 'icon': '✅', 'display_order': 80},
        {'category': 'checklist_complete', 'tier': 'silver', 'name': 'タスクマスター', 'description': '50項目完了', 'target_count': 50, 'reward_coins': 200, 'icon': '✅', 'display_order': 81},
        {'category': 'checklist_complete', 'tier': 'gold', 'name': 'タスクチャンピオン', 'description': '100項目完了', 'target_count': 100, 'reward_coins': 300, 'icon': '✅', 'display_order': 82},
        {'category': 'checklist_complete', 'tier': 'platinum', 'name': 'タスククラッシャー', 'description': '300項目完了', 'target_count': 300, 'reward_coins': 500, 'icon': '✅', 'display_order': 83},
        {'category': 'checklist_complete', 'tier': 'diamond', 'name': 'タスクアルティメット', 'description': '1000項目完了', 'target_count': 1000, 'reward_coins': 1000, 'icon': '✅', 'display_order': 84},
        
        # ===== アクセサリー実績 =====
        {'category': 'accessory', 'tier': 'bronze', 'name': 'おしゃれ初心者', 'description': '1個購入', 'target_count': 1, 'reward_coins': 100, 'icon': '🎀', 'display_order': 90},
        {'category': 'accessory', 'tier': 'silver', 'name': 'ファッションハンター', 'description': '3個購入', 'target_count': 3, 'reward_coins': 200, 'icon': '🎀', 'display_order': 91},
        {'category': 'accessory', 'tier': 'gold', 'name': 'スタイリスト', 'description': '5個購入', 'target_count': 5, 'reward_coins': 300, 'icon': '🎀', 'display_order': 92},
        {'category': 'accessory', 'tier': 'platinum', 'name': 'ファッショニスタ', 'description': '10個購入', 'target_count': 10, 'reward_coins': 500, 'icon': '🎀', 'display_order': 93},
        {'category': 'accessory', 'tier': 'diamond', 'name': 'コレクター', 'description': '20個購入', 'target_count': 20, 'reward_coins': 1000, 'icon': '🎀', 'display_order': 94},
    ]
    
    # 一括作成
    achievements = [Achievement(**data) for data in achievements_data]
    Achievement.objects.bulk_create(achievements)
    
    print(f"✅ 実績データ {len(achievements)} 件を作成しました！")


def reverse_achievements(apps, schema_editor):
    """ロールバック時に実績データを削除"""
    Achievement = apps.get_model('codemon', 'Achievement')
    Achievement.objects.all().delete()
    print("🔄 実績データを削除しました。")


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0009_merge_0006_chatscore_is_checked_0008_tutorialprogress'),
    ]

    operations = [
        migrations.RunPython(create_achievements, reverse_achievements),
    ]
