# Generated by Django 5.2.7 on 2025-11-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0008_merge_20251125_0954'),
        ('codemon', '0010_merge_20251125_0957'),
    ]

    operations = [
    ]
