# Generated by Django 5.2.6 on 2025-11-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0008_merge_20251123_2022"),
        ("codemon", "0011_merge_20251127_1025"),
        ("codemon", "0011_merge_20251127_1059"),
    ]

    operations = []
