# Generated by Django 5.2.6 on 2026-02-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codemon", "0009_merge_0008_merge_20260205_1425_0008_tutorialprogress"),
        ("codemon", "0012_add_blockly_xml_to_algorithm"),
    ]

    operations = []
