# Generated by Django 5.2.6 on 2026-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0008_merge_20260205_1425'),
        ('codemon', '0012_add_blockly_xml_to_algorithm'),
    ]

    operations = [
    ]
