# Generated by Django 5.2.6 on 2026-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0001_initial'),
    ]

    operations = [
    ]
