# Generated by Django 5.2.6 on 2026-02-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_group_delete_groupmember_group_groupmember_and_more"),
        ("codemon", "0013_merge_20260209_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial1Plus1Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=0, verbose_name="現在のステップ（0～31）"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="チュートリアル完了"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="開始日時"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_1plus1_progress",
                        to="accounts.account",
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "1+1チュートリアル進行状況",
                "verbose_name_plural": "1+1チュートリアル進行状況",
                "db_table": "tutorial_1plus1_progress",
            },
        ),
    ]
