# Generated by Django 5.2.6 on 2026-02-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemon', '0013_merge_20260206_1357'),
        ('codemon', '0014_tutorial1plus1progress'),
    ]

    operations = [
    ]
