# Generated by Django 5.2.6 on 2025-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='氏名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('account_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='アカウント種別')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='アバター画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': 'アカウント',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AiConfig',
            fields=[
                ('ai_setting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='ユーザーID')),
                ('appearance', models.CharField(default='三角', max_length=100, verbose_name='AI外見')),
                ('ai_name', models.CharField(default='codemon', max_length=50, verbose_name='AI名前')),
                ('ai_personality', models.CharField(blank=True, default='元気', max_length=100, null=True, verbose_name='AI性格')),
                ('ai_speech', models.CharField(blank=True, default='です', max_length=50, null=True, verbose_name='AI語尾')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'AI設定',
                'verbose_name_plural': 'AI設定',
                'db_table': 'ai_config',
            },
        ),
    ]
