# Generated by Django 5.2.6 on 2025-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
    ]