# Generated by Django 5.2.6 on 2025-11-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('codemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codemon.group',),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
            ],
            options={
                'verbose_name': 'グループメンバー',
                'verbose_name_plural': 'グループメンバー',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codemon.groupmember',),
        ),
    ]
