# Generated by Django 5.2.7 on 2025-11-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_type'),
        ('codemon', '0006_remove_chat_created_by_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codemon.group',),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
            ],
            options={
                'verbose_name': 'グループメンバー',
                'verbose_name_plural': 'グループメンバー',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codemon.groupmember',),
        ),
        # RemoveField(type) 操作を削除（type 列は存在しないためエラー回避）
    ]
