# Generated by Django 5.2.6 on 2025-11-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_avatar"),
        ("accounts", "0003_add_type"),
    ]

    operations = []
