# Generated by Django 5.2.6 on 2025-11-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0002_account_avatar_0003_add_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
