# Generated by Django 5.2.6 on 2025-11-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_avatar'),
    ]

    operations = [
    ]
