# Generated by Django 5.2.6 on 2025-11-23 21:05
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_auto_20251123_2100'),
    ]
    operations = [
        migrations.AddField(
            model_name='account',
            name='group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='グループID'),
        ),
    ]
