# Generated by Django 5.2.7 on 2025-11-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_avatar_remove_account_type'),
        ('accounts', '0007_add_avatar_column'),
    ]

    operations = [
    ]