# Generated by Django 5.2.6 on 2025-11-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20251125_1127'),
    ]

    operations = [
    ]