# Generated by Django 5.2.6 on 2025-11-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0009_merge_20251126_1231'),
    ]

    operations = [
    ]
