# Generated by Django 5.2.7 on 2025-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_group_id'),
        ('accounts', '0010_account_group_id'),
        ('accounts', '0010_merge_0002_initial_0009_merge_20251126_1231'),
    ]

    operations = [
    ]
