# Generated by Django 5.2.7 on 2026-01-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20251128_1247'),
        ('accounts', '0011_merge_20251128_1358'),
    ]

    operations = [
    ]
