# Generated by Django 5.2.6 on 2026-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20251128_1232'),
        ('accounts', '0012_merge_20260108_1009'),
    ]

    operations = [
    ]
